### ISSUE TITLE
iOS/ipadOS log in error : "Unknown error"

### ISSUE THREAD

**Issue by kriss6557** [wallabag/ios-app#398]
Hello,
I'm new to Wallabag.
I have installed the server as a docker container using the following docker compose:

```
version: '3'
services:
  wallabag:
    image: wallabag/wallabag:2.5.4
    container_name: wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=http://myserver.local:8200
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    ports:
      - "8200:80"
    volumes:
      - /wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: mariadb:10.8.2
    container_name: wallabag-db
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - /wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
  redis:
    image: redis:7.0.11-alpine3.17
    container_name: wallabag-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
```

My server runs on port 8200

I installed the wallabagger plugin on firefox and all runs perfectly.
I have installed the app wallabag v2 on iOS and ipadOS (wallabag v2 6.2, 9 months old) and both fail with "Unknown error".
Nothing in the docker console.
These 2 devices are on the same subnet and can access the admin portal through the web GUI.

Can it be the app being too old and not compliant anymore with the latest server's version or the custom port not managed by the app ?
Can you please help ?
